In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.1'

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [6]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [8]:
df.shape[0]

9704

In [9]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [10]:
df['fuel_type'].nunique()

2

In [11]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [14]:
(df.isnull().sum() >0).sum()

np.int64(4)

In [20]:
df['origin'].value_counts()

origin
Europe    3254
Asia      3247
USA       3203
Name: count, dtype: int64

In [21]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [24]:
initial_hp = df['horsepower'].median()
initial_hp

np.float64(149.0)

In [25]:
df['horsepower'].isna().sum()

np.int64(708)

In [28]:
frequent_hp = df['horsepower'].mode()[0]
frequent_hp

np.float64(152.0)

In [29]:
df_imputed = df.copy()

df_imputed['horsepower'].fillna(frequent_hp, inplace=True)


/tmp/ipykernel_2915/4055988944.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_imputed['horsepower'].fillna(frequent_hp, inplace=True)


In [30]:
df_imputed['horsepower'].isna().sum()

np.int64(0)

In [31]:
final_median = df_imputed['horsepower'].median()
final_median

np.float64(152.0)

In [33]:
print(final_median - initial_hp)

3.0


In [37]:
asia_df = df[df['origin']=='Asia'][['vehicle_weight', 'model_year']]
asia_df_7 = asia_df.head(7)

In [39]:
asia_df_7.reset_index(drop=True, inplace=True)

In [40]:
asia_df_7

vehicle_weight  model_year
0     2714.219310        2016
1     2783.868974        2010
2     3582.687368        2007
3     2231.808142        2011
4     2659.431451        2016
5     2844.227534        2014
6     3761.994038        2019

In [41]:
X = asia_df_7.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [42]:
XTX = X.T.dot(X)

In [43]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [44]:
import numpy as np

In [45]:
XTX_inv = np.linalg.inv(XTX)

In [46]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [47]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [48]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [49]:
w = XTX_inv.dot(X.T).dot(y)

In [50]:
w

array([0.01386421, 0.5049067 ])

In [51]:
sum_w = sum(w)

In [52]:
sum_w

np.float64(0.5187709081074016)